#!/usr/local/bin/R
args = commandArgs(trailingOnly=TRUE)
file_in=args[1]
#==========================================
r=read.table(file_in,skip=1,row.names = 1)

file_out=paste(file_in,".rf_test",sep="")
if(file.exists(file_out)){
        rm=file.remove(file_out)
}
check_FAILED=0
for(i in 1:nrow(r)){
        check=length(which(r[i,]==0))
        if(check<1){
                check_FAILED=check_FAILED+1
                write(paste("ERROR: ",row.names(r)[i]," - tree is different from all the other trees generated by another program!"),file_out,append = TRUE)
        }else if(check>1){
                check_FAILED=check_FAILED+1
                 write(paste("ERROR: ",row.names(r)[i]," - tree has more than one match among other trees generated by another program!"),file_out,append = TRUE)
        }

        #else{
        #       write(paste("GREAT!",row.names(r)[i],"has exactly one matching tree"),file_out,append = TRUE)
        #}
}

file_out=paste(file_in,".SANITY_RF_DIFF_RES",sep="")
if(check_FAILED==0){
        write("SUCCESS: SANITY_CHECK_RF: there is exactly one pair of identical trees",file_out,append = FALSE)
}else{
        write("FAIL: SANITY_CHECK_RF: either some trees do not have pairs or there is more than 1 identical tree",file_out,append = FALSE)
}
